server:
  port: 9090

spring:
  jpa:
    properties:
      .hibernate:
        .dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 309927605